/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmindigRouteImport } from './routes/admindig'
import { Route as DiagnosticofinanceiroRouteImport } from './routes/diagnosticofinanceiro'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmindigRoute = AdmindigRouteImport.update({
  id: '/admindig',
  path: '/admindig',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticofinanceiroRoute = DiagnosticofinanceiroRouteImport.update({
  id: '/diagnosticofinanceiro',
  path: '/diagnosticofinanceiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admindig': typeof AdmindigRoute
  '/diagnosticofinanceiro': typeof DiagnosticofinanceiroRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admindig': typeof AdmindigRoute
  '/diagnosticofinanceiro': typeof DiagnosticofinanceiroRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admindig': typeof AdmindigRoute
  '/diagnosticofinanceiro': typeof DiagnosticofinanceiroRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admindig'
    | '/diagnosticofinanceiro'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admindig'
    | '/diagnosticofinanceiro'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/admindig'
    | '/diagnosticofinanceiro'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmindigRoute: typeof AdmindigRoute
  DiagnosticofinanceiroRoute: typeof DiagnosticofinanceiroRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admindig': {
      id: '/admindig'
      path: '/admindig'
      fullPath: '/admindig'
      preLoaderRoute: typeof AdmindigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosticofinanceiro': {
      id: '/diagnosticofinanceiro'
      path: '/diagnosticofinanceiro'
      fullPath: '/diagnosticofinanceiro'
      preLoaderRoute: typeof DiagnosticofinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmindigRoute: AdmindigRoute,
  DiagnosticofinanceiroRoute: DiagnosticofinanceiroRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
